### ISSUE TITLE
Model specs missing in fixtures

### ISSUE THREAD

**Issue by jsalbert** [triagemd/keras-eval#85]
No model specs here:
`/github_repos/keras-eval/tmp/fixtures/models/ensemble/mobilenet_1`

Model can't be loaded.

**Comment by anirudh-challa** [comment]
I just realized that the `model_spec.json` file gets created when `script/test` is run as it is a part of `tests/conftest.py`.  I am actually wondering how anyone was able to run the notebook without running `script/test`.
