### ISSUE TITLE
Setuptools dependency in setup.py

### ISSUE THREAD

**Issue by anirudh-challa** [triagemd/keras-eval#91]
We need to figure out if need a particular setuptools version in `setup.py` as seen [here](https://github.com/triagemd/keras-eval/blob/9693d6d42630e8d78203c8124f6acba2bef58407/setup.py#L25).

The reason I added it was because of an error message similar to [this](https://stackoverflow.com/questions/51526644/how-to-install-keras-if-the-required-version-of-setuptools-is-older-than-default).

Having a particular version of setuptool as a dependency is an issue as every repository which is dependant on keras-eval will need to have that particular version of setuptools as a dependency as it is not the most updated version.  

I think one way to validate the need for setuptools would be to remove the dependency and see if anything breaks.

What do you think @adriaromero @jsalbert ?

**Comment by adriaromero** [comment]
The reason why we did not set a particular `setuptools` version is because it chooses automatically the best that fits in that moment, and everything runs well. 

What's the issue you're facing if `setuptools` version not set?

**Comment by anirudh-challa** [comment]
If it's not set during `script/up` it installs a version which is incompatible to tensroflow and we get a message like [this](https://stackoverflow.com/questions/51526644/how-to-install-keras-if-the-required-version-of-setuptools-is-older-than-default). But if you think it is not an issue I could remove it and see if everything works fine.

**Comment by adriaromero** [comment]
But I understand that tensorflow and keras work fine even this message right? It should be a big deal then.

**Comment by anirudh-challa** [comment]
Ok, I'll test it locally without it and PR if it works fine.
